apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
  namespace: ecsdemo-microservices
spec:
  selector:
    app: ecsdemo-nodejs
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000