apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: docker-getting-started
  namespace: docker-getting-started
spec:
  maxReplicas: 10
  minReplicas: 2
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker-getting-started
